name: Deploy Site
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Connect to tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Build site
        run: pnpm install -P && pnpm build
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production
          chmod 600 ~/.ssh/production
          cat >> ~/.ssh/config <<EOF
          Host production
            HostName $DEPLOY_HOST
            User ci
            IdentityFile ~/.ssh/production
            StrictHostKeyChecking no
          EOF
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
      - name: Deploy site
        run: |
          rsync -avz --delete dist/ production:/var/www/mrkirby153.com
